version: 2
jobs:
  test:
    docker:
      - image: node:20
    steps:
      - checkout
      # look for existing cache and restore if found
      - restore_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
      # install dependencies    
      - run:
          name: install dependencies
          command: yarn install
      # save any changes to the cache
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          paths: 
            - node_modules 
      - run:
          name: Node Test
          command: yarn test

  release-docker:
    docker:
      - image: benjamincaldwell/ci-scripts
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and pushing docker image
          command: ci-scripts docker/build_and_push_image --docker-images-dockerRepo benjamincaldwell/notion-hooks --
          environment:
            DOCKER_IMAGE_PLATFORM: "linux/amd64,linux/arm64"

  deploy:
    docker:
      - image: cimg/base:2022.12
    steps:
      - run:
          name: Updating docker image in k8s-config
          command: |
            curl -H "Authorization: token $GITHUB_TOKEN" -H 'Accept: application/vnd.github.v3.raw' https://api.github.com/repos/bcaldwell/k8s-config/contents/scripts/update_docker_image.sh | bash /dev/stdin commonplace/notion-hooks ${CIRCLE_SHA1}

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - release-docker:
          context: docker
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - release-docker
          filters:
            branches:
              only: main
          context: bot-github
# ---
# version: 2.1

# orbs:
#   release-management: salesforce/npm-release-management@4

# workflows:
#   version: 2
#   test-and-release:
#     jobs:
#       - release-management/test-package:
#           matrix:
#             parameters:
#               os:
#                 - linux
#                 - windows
#               node_version:
#                 - latest
#                 - lts
#                 - maintenance
#   dependabot-automerge:
#     triggers:
#       - schedule:
#           cron: '0 2,5,8,11 * * *'
#           filters:
#             branches:
#               only:
#                 - main
#     jobs:
#       - release-management/dependabot-automerge
